[package]
name = "screw-core"
edition = "2024"

[dependencies]
screw-components = { path = "../screw-components" }
hyper = { version = "1.11.0", features = ["server", "http1", "http2"] }
http-body-util = "0.1.4"
bytes = "1.12.1"
actix-router = "0.5.4"
form_urlencoded = "1.2.2"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["rt", "rt-multi-thread", "macros", "net"] }
hyper = { version = "1.11.0", features = ["client"] }
hyper-util = { version = "0.1.20", features = ["tokio"] }
