[package]
name = "screw-ws"
edition = "2024"

[dependencies]
screw-components = { path = "../screw-components" }
screw-core = { path = "../screw-core" }
hyper = { version = "1.11.0", features = ["server", "http1"] }
hyper-util = { version = "0.1.20", features = ["tokio"] }
tokio = { version = "1.53.1", features = ["rt"] }
tokio-tungstenite = { version = "0.30.0" }
futures-util = "0.3.33"

