[package]
name = "screw-ws"
edition = "2024"

[dependencies]
screw-components = { path = "../screw-components" }
screw-core = { path = "../screw-core" }
hyper = { version = "1.8.1", features = ["server", "http1"] }
hyper-util = { version = "0.1.19", features = ["tokio"] }
tokio = { version = "1.27.0", features = ["rt"] }
tokio-tungstenite = { version = "0.28.0" }
futures-util = "0.3.28"

